### ISSUE TITLE
python test fails 

### ISSUE THREAD

**Issue by xantares** [openSUSE/libzypp-bindings#22]
the python tests fail because PYTHONPATH is not set:
could do something like this
in tests/CMakeLists:
set_tests_properties (loading PROPERTIES ENVIRONMENT "PYTHONPATH=${SITE_DIR_INCLUDING_CMAKE_INSTALL_PREFIX}" )

ps: travis ?

**Comment by mlandres** [comment]
There is a  JenkinsCI between the git repo and the openSUSE build service, but nothing public so far.
